name: Update Forks
on:
  schedule:
    - cron: '35 */6 * * 1-5'
  workflow_dispatch:
  
jobs:
  update-forks:
    strategy:
      matrix:
        repo-name: ['Aegis','ScidApi','discord.js','macos-virtualbox']
    runs-on: ubuntu-latest
    steps:
      - name: Update forks
        id: update
        uses: octokit/request-action@89a1754fe82ca777b044ca8e79e9881a42f15a93
        with:
          route: POST /repos/{owner}/{repo}/merge-upstream
          owner: thispsj
          repo: ${{ matrix.repo-name }}
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.APP_TOKEN }}
